TRUNCATE TABLE public.album CASCADE;
TRUNCATE TABLE public.artist CASCADE;
TRUNCATE TABLE public.comment CASCADE;
TRUNCATE TABLE public.playlist CASCADE;
TRUNCATE TABLE public.song CASCADE;
TRUNCATE TABLE public.tag CASCADE;